name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build service
        run: dotnet build --configuration release
      - name: Build service container
        run: dotnet publish ./src/Service/Service.csproj --os linux --arch x64 /t:PublishContainer -c Release /p:ContainerImageTag=${{ github.run_id }}
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag container
        run: docker tag whats-for-lunch-service:${{ github.run_id }} ghcr.io/philliphoff/whats-for-lunch-service:${{ github.run_id }}
      - name: Push container
        run: docker push ghcr.io/philliphoff/whats-for-lunch-service:${{ github.run_id }}
